version: "3.8"
services:
  keycloak:
    image: "jboss/keycloak"
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
#
#  backend:
#    image: "node:12.19.1-alpine"
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./backend:/backend/
#