version: "3.3"
services:
  frontend:
    image: "frontend"
    stdin_open: true
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_KEYCLOAK_BASE_URL=""
      - REACT_APP_BACKEND_BASE_URL="http://backend:5001/api/v1"

  backend:
    image: "backend"
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - KEYCLOAK_BASE_URL=""
      - MONGO_DB_BASE_URL=""