version: "3.4"
services:

  frontend:
    image: "tranvutuan2001/frontend"
    stdin_open: true
    ports:
      - "5000:5000"

  backend:
    image: "tranvutuan2001/backend"
    ports:
      - "5001:5001"

  keycloak:
    image: "jboss/keycloak"
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=well
      - KEYCLOAK_PASSWORD=whale
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
      - KEYCLOAK_FRONTEND_URL=http://license-game.cf/keycloak
    volumes:
      - ./realm-export.json:/tmp/realm-export.json

  mongo_db:
    image: "mongo:4.2-bionic"
    ports:
      - "27017:27017"

  mongo_db_web_interface:
    image: "mongo-express"
    ports:
      - "4000:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db

  nginx:
    image: "nginx:1.18.0-alpine"
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

#  dev nginx
#  nginx:
#    image: "nginx:1.18.0-alpine"
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx.conf.dev:/etc/nginx/conf.d/default.conf