version: "3.3"
services:
#  frontend:
#    image: "frontend"
#    stdin_open: true
#    build:
#      context: .
#      dockerfile: ./frontend/Dockerfile
#    ports:
#      - "5000:5000"
#    environment:
#      - REACT_APP_KEYCLOAK_BASE_URL=""
#      - REACT_APP_BACKEND_BASE_URL=""

#  backend:
#    image: "backend"
#    build:
#      context: .
#      dockerfile: ./backend/Dockerfile
#    ports:
#      - "5001:5001"
#    environment:
#      - KEYCLOAK_BASE_URL=""
#      - MONGO_DB_BASE_URL=""

  keycloak:
    image: "jboss/keycloak"
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json

  mongo_db:
    image: "mongo:4.2-bionic"
    ports:
      - "27017:27017"

  mongo_db_web_interface:
    image: "mongo-express"
    ports:
      - "4000:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db