exports.COMPATIBILITY_TABLE = {
  "cc_zero": {
    "cc_zero": "cc_zero",
    "cc_by": "cc_by",
    "cc_by_sa": "cc_by_sa",
    "cc_by_nc": "cc_by_nc",
    "cc_by_nd": false,
    "cc_by_nc_sa": "cc_by_nc_sa",
    "cc_by_nc_nd": false,
  },
  "cc_by": {
    "cc_zero": "cc_by",
    "cc_by": "cc_by",
    "cc_by_sa": "cc_by_sa",
    "cc_by_nc": "cc_by_nc",
    "cc_by_nd": false,
    "cc_by_nc_sa": "cc_by_nc_sa",
    "cc_by_nc_nd": false,
  },
  "cc_by_sa": {
    "cc_zero": "cc_by_sa",
    "cc_by": "cc_by_sa",
    "cc_by_sa": "cc_by_sa",
    "cc_by_nc": false,
    "cc_by_nd": false,
    "cc_by_nc_sa": false,
    "cc_by_nc_nd": false,
  },
  "cc_by_nc": {
    "cc_zero": "cc_by_nc",
    "cc_by": "cc_by_nc",
    "cc_by_sa": false,
    "cc_by_nc": "cc_by_nc",
    "cc_by_nd": false,
    "cc_by_nc_sa": "cc_by_nc_sa",
    "cc_by_nc_nd": false,
  },
  "cc_by_nd": {
    "cc_zero": false,
    "cc_by": false,
    "cc_by_sa": false,
    "cc_by_nc": false,
    "cc_by_nd": false,
    "cc_by_nc_sa": false,
    "cc_by_nc_nd": false,
  },
  "cc_by_nc_sa": {
    "cc_zero": "cc_by_nc_sa",
    "cc_by": "cc_by_nc_sa",
    "cc_by_sa": false,
    "cc_by_nc": "cc_by_nc",
    "cc_by_nd": false,
    "cc_by_nc_sa": "cc_by_nc_sa",
    "cc_by_nc_nd": false,
  },
  "cc_by_nc_nd": {
    "cc_zero": false,
    "cc_by": false,
    "cc_by_sa": false,
    "cc_by_nc": false,
    "cc_by_nd": false,
    "cc_by_nc_sa": false,
    "cc_by_nc_nd": false,
  },
};